name: Padavan_3.4_kernal_toolchain

on: 
#  release:
#    types: [published]
#  push:
#    tags:
#    - 'v*'
  workflow_dispatch:
  watch:
    types: [started]
env:
  src_dir: /opt/rt-n56u
  build_dir: /opt/rt-n56u/toolchain-mipsel
  toolchain_dir: /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
  src_git: https://github.com/vipshmily/Padavan-3.4-KVR.git
jobs:
  build:
    name: Build Padavan toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Clone source code
        run: |
          git clone --depth=1 $src_git $src_dir
      - name: Build toolchain
        run: |
          cd $build_dir
          ./clean_toolchain
          ./build_toolchain
          cd $toolchain_dir
          tar cJf ../mipsel-linux-uclibc-gcc13.2.tar.xz *
      - uses: actions/upload-artifact@v3
        with:
          name: toolchain
          path: ${{ env.build_dir }}/mipsel-linux-uclibc-gcc13.2.tar.xz
      - uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.build_dir }}/mipsel-linux-uclibc-gcc8.3.tar.xz
          tag: toolchain
          overwrite: true
