name: Padavan_4.4_kernal_toolchain

on: 
  workflow_dispatch:
env:
  SRC_DIR: /opt/rt-n56u
  CT_DIR: crosstool-ng
  TC_DIR: crosstool-ng/toolchain-mipsel
  BD_DIR: crosstool-ng/toolchain-mipsel/toolchain-3.4.x
  CT_URL: https://github.com/vipshmily/Padavan-KVR.git
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mipsel-linux-uclibc-3.4]
    steps:
      - uses: actions/checkout@main
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Clone source code
        run: |
          mkdir -p $CT_DIR
          git clone --depth=1 $CT_URL $CT_DIR
      - name: Build toolchain
        run: |
          cd $SRC_DIR
          make toolchain/build
          cd $BD_DIR
          tar cJf ${{ matrix.target }}.tar.xz *
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: ${{ env.BD_DIR}}/${{ matrix.target }}.tar.xz
      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: ${{ env.BD_DIR}}/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true
