name: build toolchain

on:
  workflow_dispatch:
env:
  CT_DIR: crosstool-ng
  CT_URL: https://github.com/vipshmily/padavan-4.4.git
  TC_DIR: crosstool-ng/toolchain
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [mipsel-linux-uclibc, mipsel-linux-musl, mipsel-linux-uclibc-gcc7, mipsel-linux-musl-gcc7, mipsel-linux-uclibc-gcc13, mipsel-linux-musl-gcc13]
    steps:
      - uses: actions/checkout@main
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install unzip libtool-bin ccache curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio bc zip git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: Clone source code
        run: |
          mkdir -p $CT_DIR
          git clone --depth=1 $CT_URL $CT_DIR
      - name: Build toolchain
        run: |
          make CT_TARGET=${CT_TARGET}
          cd toolchain-mipsel
          tar cJf ../${CT_TARGET}.tar.xz *
        env:
          CT_TARGET: ${{ matrix.target }}
        working-directory: ${{ env.TC_DIR}}
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}
          path: ${{ env.TC_DIR}}/${{ matrix.target }}.tar.xz
      - uses: ncipollo/release-action@main
        with:
          tag: toolchain
          artifacts: ${{ env.TC_DIR}}/${{ matrix.target }}.tar.xz
          allowUpdates: true
          omitBodyDuringUpdate: true
